### ISSUE TITLE
population initialization

### ISSUE THREAD

**Issue by profeliasjof** [xKuZz/pyade#4]
The function init_population(...) uses np.random.randn() and forces the values to stay within the limits. But this does not sample the entire search space bounded by the bounds. My suggestion is a function like this:

def init_population(population_size: int, individual_size: int,
                    bounds: Union[np.ndarray, list]) -> np.ndarray:
    population = []
    for _ in range(population_size):
        x = []
        for i in range(individual_size):
            xi = np.random.rand() * (bounds[i][1]-bounds[i][0]) + bounds[i][0]
            gen.append(xi)
        population.append(x)
    population = np.array(population)
    return population

**Comment by HeorhiiS** [comment]
Same issue, code in this repository fails to perform proper search because of this hurdle. I'm not sure if authors have abandoned the project but if they haven't please take a look at the population initialization piece.
